@apiPoint = http://localhost:4000/api/aktien
@aktieId = 62b717cebb610b2b84ceeef1
@isin = DE000STRA555

### GET
GET {{apiPoint}}

### GET aktie by id
GET {{apiPoint}}/{{aktieId}}

### GET aktie by isin
GET {{apiPoint}}/isin/{{isin}}